/*
 * Endpoint for establishing and maintaining an encrypted client-server session
 *
 * This endpoint establishes an end-to-end encrypted client-server session after authenticating the client with its Id Certification Token (Client_ICT). After the successful exchange of DH parameters, the client can communicate with the server, upload, download or delete files on the server with all communication being encrypted on application layer.
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"log"
	"net/http"
)

// Handle GET "/ping" request
func Ping(w http.ResponseWriter, r *http.Request) {
	log.Printf("Received ping GET request")
	w, _ = DataEndpointHandler(w, r, "/ping", "get")
}

// Handle OPTIONS "/ping" request
func PingOptions(w http.ResponseWriter, r *http.Request) {
	origin := r.Header.Get("Origin")
	log.Print("origin: " + origin)
	if origin != "" {
		w.Header().Set("Access-Control-Allow-Origin", origin)
	}
	w.Header().Set("Access-Control-Allow-Methods", "GET, OPTIONS")
	w.Header().Set("Access-Control-Allow-Headers", "x-e2e-session, x-publickeyenc, x-publickeymac, signature")
	w.WriteHeader(http.StatusNoContent)

	return
}
